services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.local.frontend
    ports:
      - "3001:3001"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: ../docker/Dockerfile.local.api
    ports:
      - "8000:8000"
    depends_on:
      - model
    volumes:
      - ./data:/app/data:rw
    environment:
      - MODEL_URL=http://model:5000/predict
      - LOG_PATH=/app/data/simulation/current.jsonl
      - MODEL_NAME=loan-xgb-tuning
      - MODEL_VERSION=prod-1
      - FEATURE_PIPELINE_VERSION=local-dev

  model:
    build:
      context: ./model
      dockerfile: ../docker/Dockerfile.local.model
    ports:
      - "5000:5000"

  loan-monitor:
    build:
      context: ./monitoring
      dockerfile: ../docker/Dockerfile.local.monitoring
    ports:
      - "5003:5003"
    environment:
      - REF_DATA_PATH=/app/data/simulation/reference_data.csv
      - CURR_DATA_PATH=/app/data/simulation/prediction_dev_log.csv
      - PORT=5003
    volumes:
      - ./data:/app/data:rw