name: CI/CD - Model
on:
  push:
    paths: ['model/**', '.github/workflows/model.yml']
  workflow_call: {}
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REPO: ${{ secrets.ARTIFACT_REPO }}
  SVC: loan-model
  IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/loan-model:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read, id-token: write }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push model image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.model
          push: true
          tags: ${{ env.IMAGE }}

      - name: Deploy Cloud Run (Model, private)
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SVC }}
          image: ${{ env.IMAGE }}
          region: ${{ env.REGION }}
          flags: >
            --ingress=internal-and-cloud-load-balancing
            --no-allow-unauthenticated
            --min-instances=1
            --concurrency=20
            --cpu=1 --memory=512Mi

      - name: Output MODEL_URL
        id: model
        run: |
          URL=$(gcloud run services describe ${{ env.SVC }} --region ${{ env.REGION }} \
            --format='value(status.url)')
          echo "url=$URL" >> $GITHUB_OUTPUT