name: Scheduled Retraining

on:
  schedule:
    # 1st of every month at 00:00 UTC
    - cron: '0 0 1 * *'

permissions:
  contents: read
  actions: write

jobs:
  env:
    GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    BIGQUERY_DATASET: 'loan_prediction_dataset'
    DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
    DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
    MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
    MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
    MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/MLOps-Loan-Approval.mlflow

  retrain_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 381.0.0'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r model/requirements.txt
          pip install "dvc[http]" python-dotenv mlflow

      - name: Configure DVC remote (DagsHub)
        run: |
          dvc remote add -f dagshub https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Loan_Approval_Model.dvc

      - name: Pull DVC data
        run: dvc pull -v

      - name: Run Retraining Script
        id: run-script
        run: |
          python model/retraining_pipeline_prod.py

      - name: Push DVC data changes to remote
        run: |
          git add .dvc .dvc.lock
          git commit -m "Auto commit new data artifacts from retraining pipeline" || echo "No changes to commit"
          dvc push -v
          git push || echo "No git changes to push"

  trigger_model_deployment:
    needs: retrain_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Model Deployment Workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'model.yml',
              ref: context.ref.replace('refs/heads/', ''),
            });
